import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Navbar } from '../components/Navbar'
import { PromptPanel } from '../components/PromptPanel'
import { HistoryPanel } from '../components/HistoryPanel'
import { ModelViewer } from '../components/ModelViewer'
import { ModelEditorControls } from '../components/ModelEditorControls'
import { useModelGenerator } from '../hooks/useModelGenerator'
import type { ModelTransform } from '../types'

const formatMetadataValue = (value: unknown) => {
  if (value === null || value === undefined) return '—'
  if (typeof value === 'object') {
    try {
      return JSON.stringify(value, null, 2)
    } catch {
      return String(value)
    }
  }
  return String(value)
}

const DEFAULT_TRANSFORM: ModelTransform = {
  rotation: { x: 0, y: 0, z: 0 },
  scale: 1,
  baseColor: '#60a5fa',
}

export const Home = () => {
  const {
    history,
    selectedModel,
    selectModel,
    generateModel,
    clearHistory,
    isGenerating,
    isHistoryLoading,
    error,
    resetError,
  } = useModelGenerator()

  const [transform, setTransform] = useState<ModelTransform>(DEFAULT_TRANSFORM)

  const handleGenerate = async (prompt: string) => {
    await generateModel(prompt)
    setTransform(DEFAULT_TRANSFORM)
  }

  const handleSelect = (id: string) => {
    selectModel(id)
    setTransform(DEFAULT_TRANSFORM)
  }

  const metadataEntries = useMemo(() => {
    if (!selectedModel?.metadata) return []
    return Object.entries(selectedModel.metadata)
  }, [selectedModel])

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-sky-950 text-slate-100">
      <Navbar />
      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 pb-12 pt-28 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,420px)_1fr]">
          <div className="flex flex-col gap-6">
            <PromptPanel
              isGenerating={isGenerating}
              onGenerate={handleGenerate}
              error={error}
              onResetError={resetError}
            />
            <HistoryPanel
              items={history}
              selectedId={selectedModel?.id ?? null}
              onSelect={handleSelect}
              onRegenerate={handleGenerate}
              onClear={clearHistory}
              isLoading={isHistoryLoading}
            />
          </div>
          <div className="flex flex-col gap-6">
            <ModelViewer
              modelUrl={selectedModel?.url ?? null}
              transform={transform}
              isLoading={isGenerating}
            />
            <ModelEditorControls transform={transform} onTransformChange={setTransform} />
            <motion.section
              layout
              className="rounded-3xl border border-slate-700 bg-slate-900/70 p-6 shadow-lg shadow-sky-900/20 backdrop-blur"
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ type: 'spring', stiffness: 160, damping: 20 }}
            >
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-semibold text-slate-100">Model metadata</h2>
                  <p className="mt-1 text-sm text-slate-300">
                    Insights generated by the AI pipeline for the current model.
                  </p>
                </div>
                {selectedModel && (
                  <span className="rounded-full bg-slate-800/70 px-3 py-1 text-xs font-medium text-sky-200">
                    {new Date(selectedModel.createdAt).toLocaleTimeString([], {
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </span>
                )}
              </div>

              {selectedModel ? (
                <div className="mt-4 space-y-4">
                  <div className="rounded-2xl bg-slate-950/60 p-4 text-sm text-slate-200">
                    <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                      Prompt
                    </p>
                    <p className="mt-1 whitespace-pre-wrap leading-relaxed">
                      {selectedModel.prompt}
                    </p>
                  </div>
                  <div className="grid gap-3 md:grid-cols-2">
                    {metadataEntries.length > 0 ? (
                      metadataEntries.map(([key, value]) => (
                        <div
                          key={key}
                          className="rounded-2xl border border-slate-700 bg-slate-950/60 p-4 text-sm text-slate-200 shadow-sm shadow-sky-900/10"
                        >
                          <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                            {key}
                          </p>
                          <pre className="mt-2 whitespace-pre-wrap break-words text-sm leading-snug text-slate-200">
                            {formatMetadataValue(value)}
                          </pre>
                        </div>
                      ))
                    ) : (
                      <div className="rounded-2xl border border-dashed border-slate-600 bg-slate-950/60 p-4 text-sm text-slate-400">
                        No additional metadata provided for this model.
                      </div>
                    )}
                  </div>
                </div>
              ) : (
                <div className="mt-6 rounded-2xl border border-dashed border-slate-600 bg-slate-950/60 p-6 text-sm text-slate-400">
                  Generate an aircraft to see AI-derived specs and material hints.
                </div>
              )}
            </motion.section>
          </div>
        </div>
      </main>
    </div>
  )
}

